/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Clases.Cuenta;
/**
 * La clase `GUI_Pin_Transaccion` representa la interfaz gráfica para validar el PIN antes de realizar una transacción.
 * Puede ser utilizada para transferencias, pagos de servicios o pagos de tarjetas.
 *
 * <p><strong>Atributos:</strong></p>
 * <ul>
 *   <li>{@code istransferencia} - Entero que indica el tipo de transacción (0 para transferencia, 1 para pago de servicio, 2 para pago de tarjeta).</li>
 *   <li>{@code cuenta_final} - Objeto `Cuenta` representando la cuenta del cliente.</li>
 *   <li>{@code menu_transferencias} - Objeto `GUI_Transferencias` para transferencias.</li>
 *   <li>{@code menu_servicios} - Objeto `GUI_Pago_Servicios` para pagos de servicios.</li>
 *   <li>{@code menu_Tarjetas} - Objeto `GUI_Pago_Tarjetas` para pagos de tarjetas.</li>
 * </ul>
 *
 * <p><strong>Métodos:</strong></p>
 * <ul>
 *   <li>{@code get_istransferencia()} - Retorna el tipo de transacción.</li>
 *   <li>{@code set_Datos(Cuenta cuenta_final, GUI_Transferencias menu_transferencias)} - Inicializa los datos para transferencias.</li>
 *   <li>{@code set_Datos(Cuenta cuenta_final, GUI_Pago_Servicios menu_servicios)} - Inicializa los datos para pagos de servicios.</li>
 *   <li>{@code set_Datos(Cuenta cuenta_final, GUI_Pago_Tarjetas menu_Tarjetas)} - Inicializa los datos para pagos de tarjetas.</li>
 * </ul>
 * 
 * @author josef
 */
public class GUI_Pin_Transaccion extends javax.swing.JFrame {

    private int istransferencia; //0 es transferencia, 1 es pago de servicio y 2 es pago de tarjeta
    private Cuenta cuenta_final;
    private GUI_Transferencias menu_transferencias;
    private GUI_Pago_Servicios menu_servicios;
    private GUI_Pago_Tarjetas menu_Tarjetas;
    /**
     * Creates new form Validar_Pin_Transaccion
     */
    public GUI_Pin_Transaccion(){
        initComponents();
    }

    
    public int get_istransferencia(){
        return istransferencia;
    }
    
    public void set_Datos(Cuenta cuenta_final, GUI_Transferencias menu_transferencias){
        this.cuenta_final = cuenta_final;
        this.menu_transferencias = menu_transferencias;
        istransferencia = 0;
    }
    
    public void set_Datos(Cuenta cuenta_final, GUI_Pago_Servicios menu_servicios){
        this.cuenta_final = cuenta_final;
        this.menu_servicios = menu_servicios;
        istransferencia = 1;
    }
    
        public void set_Datos(Cuenta cuenta_final, GUI_Pago_Tarjetas menu_Tarjetas){
        this.cuenta_final = cuenta_final;
        this.menu_Tarjetas = menu_Tarjetas;
        istransferencia = 2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Validar Pin");

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel2.setText("PIN:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            int pin_ingresado = Integer.parseInt(jPasswordField1.getText().replace(" ", ""));
            if(pin_ingresado == cuenta_final.getPinTransaccion()){
                if (istransferencia == 0){
                    menu_transferencias.transferir();
                    dispose();
                    menu_transferencias.cerrar();
                }
                else if (istransferencia == 1) {
                    menu_servicios.pagar();
                    dispose();
                    menu_servicios.cerrar();
                }
                else{
                    menu_Tarjetas.pagar();
                    dispose();
                    menu_Tarjetas.cerrar();
                }
            }
            else jPasswordField1.setText("");
        }catch(Exception e)
        {
            e.printStackTrace();
            jPasswordField1.setText("");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Pin_Transaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Pin_Transaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Pin_Transaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Pin_Transaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Pin_Transaccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
