/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.Cliente;
import Clases.Comprobante;
import Clases.Cuenta;
import Clases.Pago;
import Clases.Servicio;
import Clases.Tarjeta;
import Clases.Tarjeta_Credito;
import static java.lang.Integer.parseInt;

/**
 * La clase `GUI_Pago_Servicios` representa la interfaz gráfica para realizar pagos de servicios.
 * Esta interfaz permite al usuario seleccionar un servicio, ingresar el monto a pagar y el método de pago.
 * Además, realiza validaciones y actualiza la información de la cuenta y el historial de movimientos.
 *
 * <p><strong>Atributos:</strong></p>
 * <ul>
 *   <li>{@code pagos} - Arreglo de objetos `Pago`.</li>
 *   <li>{@code servicios} - Arreglo de objetos `Servicio`.</li>
 *   <li>{@code cuenta_final} - Objeto `Cuenta` representando la cuenta del cliente.</li>
 *   <li>{@code cliente_final} - Objeto `Cliente` representando al cliente.</li>
 *   <li>{@code tarjetas} - Arreglo de objetos `Tarjeta_Credito`.</li>
 *   <li>{@code menu_principal} - Objeto `GUI_Ventana_Principal` representando el menú principal.</li>
 * </ul>
 *
 * <p><strong>Métodos:</strong></p>
 * <ul>
 *   <li>{@code InicializarTodo(Pago[] pagos, Servicio[] servicios, Cuenta cuenta_final, Cliente cliente_final, Tarjeta_Credito[] tarjetas, GUI_Ventana_Principal menu_principal)} - Inicializa los datos de la interfaz.</li>
 *   <li>{@code pagar()} - Realiza el proceso de pago y actualiza la información de la cuenta y el historial.</li>
 *   <li>{@code cerrar()} - Cierra la interfaz y actualiza la información en la ventana principal.</li>
 * </ul>
 *
 * @author EJFR0
 */
public class GUI_Pago_Servicios extends javax.swing.JFrame implements Interfaz{
    private Pago[] pagos;
    private Servicio[] servicios;
    private Cuenta cuenta_final;
    private Cliente cliente_final;
    private Tarjeta_Credito[] tarjetas;
    private GUI_Ventana_Principal menu_principal;
    /**
     * Creates new form Pago_Servicios
     */
    public GUI_Pago_Servicios() {
        initComponents();
    }
    public void InicializarTodo (Pago[] pagos, Servicio[] servicios ,Cuenta cuenta_final, Cliente cliente_final, Tarjeta_Credito[] tarjetas, GUI_Ventana_Principal menu_principal) {
        this.pagos = pagos;
        this.servicios = servicios;
        this.cuenta_final = cuenta_final;
        this.cliente_final = cliente_final;
        this.tarjetas = tarjetas;
        this.menu_principal = menu_principal;
        
        for (Servicio servicio : servicios) {
            jComboBox1.addItem(servicio.getNombre());
        }
        
        jComboBox2.addItem("Tarjeta Débito");
        
        for (Tarjeta tarjeta : cuenta_final.getTarjetas()){
            jComboBox2.addItem("Tarjeta N° " + tarjeta.getN_Tarjeta());
        }
        
        
        int index = jComboBox1.getSelectedIndex();
        jLabel6.setText("Pago mínimo: " + pagos[index].getPagoMin());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Pago de servicios");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel2.setText("Seleccionar Servicio:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel3.setText("Monto a pagar:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel4.setText("Dato Adicional");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel7.setText("Método de pago:");

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel5)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //VALIDAR DATOS
        int index = jComboBox1.getSelectedIndex();
        int index2 = jComboBox2.getSelectedIndex()-1;
        if (jComboBox2.getSelectedIndex() == 0){
            try
        {
            pagos[index].setMonto(parseInt(jTextField1.getText()));
            if (pagos[index].getMonto() < pagos[index].getPagoMin()){
                jTextField1.setText("");
                return;
            }
            else if (cuenta_final.getSaldo() < pagos[index].getMonto()) {
                jLabel8.setText("Saldo insuficiente");
                return;
            }
            else{
                GUI_Pin_Transaccion menu_validar = new GUI_Pin_Transaccion();
                menu_validar.setVisible(true);
                menu_validar.set_Datos(cuenta_final, this);
                menu_validar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
            
        }catch(Exception e)
        {
            jTextField1.setText("");
        }
        }
        else {
            try
        {
            pagos[index].setMonto(parseInt(jTextField1.getText()));
            if (pagos[index].getMonto() < pagos[index].getPagoMin()){
                jTextField1.setText("");
                return;
            }
            else if (pagos[index].getMonto() > cuenta_final.getTarjetas().get(index2).getLimiteCredito()){
                jLabel8.setText("Saldo insuficiente");
                return;
            }
            else{
                GUI_Pin_Transaccion menu_validar = new GUI_Pin_Transaccion();
                menu_validar.setVisible(true);
                menu_validar.set_Datos(cuenta_final, this);
                menu_validar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
            
        }catch(Exception e)
        {
            jTextField1.setText("");
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void pagar(){
        int index = jComboBox1.getSelectedIndex();
        int index2 = jComboBox2.getSelectedIndex()-1;
        if (jComboBox2.getSelectedIndex() == 0) {
            cuenta_final.setSaldo(cuenta_final.getSaldo()-pagos[index].getMonto());
            //Creamos el comprobante
            Comprobante comprobante_final = new Comprobante();
            comprobante_final.set_monto(-pagos[index].getMonto());
            comprobante_final.set_id(cuenta_final.getMovimientos().size()+1);
            comprobante_final.set_descripcion("Pago de "+ servicios[index].getNombre());
            //Agrega el comprobante en el historial de la cuenta
            cuenta_final.setMovimientos(comprobante_final);
        }
        else {
            cuenta_final.getTarjetas().get(index2).setLimiteCredito(cuenta_final.getTarjetas().get(index2).getLimiteCredito()-pagos[index].getMonto());
            cuenta_final.getTarjetas().get(index2).setSaldo(cuenta_final.getTarjetas().get(index2).getSaldo()+pagos[index].getMonto());
            //Creamos el comprobante
            Comprobante comprobante_final = new Comprobante();
            comprobante_final.set_monto(-pagos[index].getMonto());
            comprobante_final.set_id(cuenta_final.getMovimientos().size()+1);
            comprobante_final.set_descripcion("Pago de "+ servicios[index].getNombre() + "  (TC)");
            //Agrega el comprobante en el historial de la cuenta
            cuenta_final.setMovimientos(comprobante_final);
        }
    }
    @Override
    public void cerrar(){
        menu_principal.set_Usuario_Saldo();
        dispose();
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int index = jComboBox1.getSelectedIndex();
        jLabel6.setText("Pago mínimo: " + pagos[index].getPagoMin());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        int index2 = jComboBox2.getSelectedIndex();
        int index = jComboBox1.getSelectedIndex();
        pagos[index].setMetodoPago(index2);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Pago_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Pago_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Pago_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Pago_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Pago_Servicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
